apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowstorm
spec:
  selector:
    matchLabels:
      app: snowstorm
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: snowstorm
        tier: frontend
    spec:
      containers:
      - name: snowstorm
        image: gpalli/snowstorm
        envFrom:
          - configMapRef:
            name: snowstorm-config
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
