apiVersion: v1
kind: Service
metadata:
  annotations:
  name: snowstorm
spec:
  selector:
    app: snowstorm
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
